# -*- coding: utf-8 -*-
"""Project.1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xUSgyxS5Awrf7blogUknRuS_uuhFzWPd

Project Title :
    Decoding Emotions Through Sentiment Analysis of Social Media Conversations

🧠 Project Overview

This project focuses on using Natural Language Processing (NLP) to analyze and classify the emotional tone of social media posts—specifically tweets—into categories like positive, negative, or neutral. By training machine learning models on real-world data, we aim to understand public sentiment and how people express emotions online.


📌 Problem Statement

  Social media platforms like Twitter are rich sources of public opinion. However, manually analyzing thousands of posts is impractical. This project automates the process of sentiment detection, enabling:

I. Businesses to monitor customer feedback

II. Researchers to study public mood

III. Governments to track reactions to policies or events


📊 Dataset Used

We used the Twitter US Airline Sentiment Dataset, which contains over 14,000 tweets labeled as:

          Positive

          Negative

          Neutral

Each tweet is associated with a major U.S. airline and includes the tweet text and sentiment label.



🔄 Methodology

1. Data Preprocessing

    Converted text to lowercase

    Removed URLs, mentions, hashtags, punctuation

    Removed stopwords (common words like “the”, “is”)

    Tokenized and cleaned the text for analysis

2. Feature Extraction

Used TF-IDF (Term Frequency–Inverse Document Frequency) to convert text into numerical vectors that represent the importance of words in each tweet.

3. Model Training

  Trained a Logistic Regression classifier to predict sentiment based on the tweet content.

  Split the dataset into training and testing sets (80/20 split).

4. Evaluation

Evaluated the model using:

      Accuracy

      Precision, Recall, F1-score

      Confusion Matrix
📈 Results

  The model achieved strong performance in identifying negative tweets (which were the majority class).

  The confusion matrix showed that most misclassifications occurred between neutral and positive tweets, which is expected due to their subtle differences.

🧪 Real-World Application

This model can be extended to:

I. Monitor brand reputation in real-time

II. Analyze political sentiment during elections

III. Track emotional trends during global events (e.g., pandemics, sports)



🛠 Tools & Technologies

    Category	Tools Used
    Language	Python
    Libraries	nltk, sklearn, pandas, matplotlib, seaborn
    Model	Logistic Regression
    Vectorization	TF-IDF
    Dataset	Twitter US Airline Sentiment (Kaggle)Future Enhancements

  Use deep learning models like LSTM or BERT for better accuracy

  Scrape live tweets using snscrape for real-time sentiment tracking

  Deploy the model as a web app using Streamlit or Flask

Step 1: Import Required Libraries
"""

import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix

""" Step 2: Load Dataset (make sure 'Tweets.csv' is uploaded)

"""

from google.colab import files
upload=files.upload()

import pandas as pd
df = pd.read_csv("twitter.csv")
print(df)

"""1.  Preprocess text (lowercase, remove stopwords, punctuation)

"""

stop_words = set([
    'i','me','my','myself','we','our','you','your','he','his','him',
    'she','her','it','its','they','them','this','that','am','is','are',
    'was','were','be','been','being','have','has','had','do','does','did',
    'a','an','the','and','but','if','or','because','as','until','while',
    'of','at','by','for','with','about','between','into','through',
    'during','before','after','to','from','up','down','in','out','on',
    'off','over','under','again','then','once','here','there','when',
    'where','why','how','all','any','both','each','few','more','most',
    'other','some','such','no','nor','not','only','own','same','so',
    'than','too','very','can','will','just','don','should'
])

def clean_text(text):
    text = text.lower()  # lowercase
    text = re.sub(r"http\S+", "", text)  # remove URLs
    text = re.sub(r"[^a-z\s]", "", text)  # remove punctuation/numbers
    return " ".join([word for word in text.split() if word not in stop_words])

df["clean_text"] = df["text"].apply(clean_text)

"""2. TF-IDF or word embeddings for vectorization"""

vectorizer = TfidfVectorizer(max_features=3000)
X = vectorizer.fit_transform(df["clean_text"])
y = df["airline_sentiment"]

"""3. Train sentimentclassification"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = MultinomialNB()
model.fit(X_train, y_train)

"""Evasluate the model"""

y_pred = model.predict(X_test)

print("🔍 Classification Report:\n")
print(classification_report(y_test, y_pred))

"""Confusion Matrix"""

conf_matrix = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6, 4))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues',
            xticklabels=model.classes_, yticklabels=model.classes_)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""4. Vizualize frequent words using word clouds"""

def word_cloud(sentiment):
    text = " ".join(df[df['airline_sentiment'] == sentiment]['clean_text'])
    wc = WordCloud(width=800, height=400, background_color="white").generate(text)
    plt.figure(figsize=(10, 5))
    plt.imshow(wc, interpolation='bilinear')
    plt.axis('off')
    plt.title(f"{sentiment.capitalize()} Word Cloud")
    plt.show()

word_cloud("positive")
word_cloud("negative")
word_cloud("neutral")

"""5. Test model with custom tweets and examples"""

#Test on Custom Tweet
def predict_sentiment(tweet):
    cleaned = clean_text(tweet)
    vector = vectorizer.transform([cleaned])
    return model.predict(vector)[0]

# Example test
tweet = "I had a wonderful flight experience with the staff being very friendly!"
print("✈ Custom Tweet:", tweet)
print("Predicted Sentiment:", predict_sentiment(tweet))